name: Deploy HTML version to GitHub page
on: [push]
jobs:
  Org-mode-to-HTML:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install emacs
      - run: emacs index.org --batch -f org-html-export-to-html --kill
