name: Deploy HTML version to GitHub page
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: org-mode to HTML
    - run: apt-get install emacs
    - run: emacs index.org --batch -f org-html-export-to-html --kill
